# Generated by Django 4.2.5 on 2024-06-18 13:57

from django.db import migrations, models
import django.db.models.deletion
import habit.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnjoyableHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250, verbose_name='Действие приятной привычки')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезнаые привычки',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время когда выполняется привычка')),
                ('time_complete', models.TimeField(validators=[habit.validators.validate_max_time], verbose_name='Время на выполнение')),
                ('periodicity', models.IntegerField(choices=[(1, 'Раз в день'), (2, 'Раз в два дня'), (3, 'Раз в три дня'), (4, 'Раз в четыре дня'), (5, 'Раз в пять дней'), (6, 'Раз в шесть дней'), (7, 'Раз в неделю')], default=1, validators=[habit.validators.validate_max_date], verbose_name='Периодичность')),
                ('sign_publicity', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вознаграждение')),
                ('sign_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('enjoyable_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.enjoyablehabit', verbose_name='приятная привычка')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habit.habit', verbose_name='Связанная привычка')),
                ('useful_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.usefulhabit', verbose_name='полезная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
