# Generated by Django 4.2.5 on 2024-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(verbose_name='Время когда выполняется привычка'),
        ),
    ]
