# Generated by Django 4.2.5 on 2024-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.PositiveIntegerField(default='503234730', verbose_name='id для телеграма'),
        ),
    ]
